const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function absoluteUrl(path = '/') {
  const base = String(process.env.FRONTEND_URL || 'https://skyesim.netlify.app').replace(/\/$/, '');
  return /^https?:\/\//i.test(path) ? path : `${base}/${String(path).replace(/^\//, '')}`;
}

function layout({ eyebrow='КОМАНДА SIGNAL', title, intro='', content='', action=null, footer='' }) {
  const logo=absoluteUrl('/signal-premium-logo.png');
  const button=action?.url?`<table role="presentation" cellspacing="0" cellpadding="0" style="margin:28px 0"><tr><td style="border-radius:13px;background:#4f6cff"><a href="${escapeHtml(absoluteUrl(action.url))}" style="display:inline-block;padding:14px 23px;color:#fff;text-decoration:none;font-size:14px;font-weight:800">${escapeHtml(action.label||'Відкрити')}</a></td></tr></table>`:'';
  return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light only"></head><body style="margin:0;padding:0;background:#eef2f8;color:#172033;font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef2f8"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border:1px solid #dfe6f1;border-radius:24px;overflow:hidden;box-shadow:0 18px 48px rgba(21,35,66,.12)"><tr><td style="padding:24px 26px;background:linear-gradient(135deg,#071126,#102b5d)"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td><img src="${logo}" width="58" height="58" alt="Signal" style="display:block;border:0;border-radius:15px"></td><td style="padding-left:14px"><div style="font-size:21px;font-weight:900;color:#fff">Signal</div><div style="margin-top:3px;color:#9fb8e7;font-size:12px">Глобальний eSIM-сервіс</div></td></tr></table></td></tr><tr><td style="padding:30px 26px"><div style="font-size:11px;letter-spacing:1.5px;color:#6558df;font-weight:900">${escapeHtml(eyebrow)}</div><h1 style="font-size:26px;line-height:1.25;margin:10px 0 14px;color:#111a2c">${escapeHtml(title)}</h1>${intro?`<p style="font-size:15px;line-height:1.7;color:#526078;margin:0 0 22px">${escapeHtml(intro)}</p>`:''}${content}${button}<div style="margin-top:28px;padding-top:20px;border-top:1px solid #edf0f5;color:#78859a;font-size:12px;line-height:1.65">${footer||'З повагою,<br><strong>Команда Signal</strong><br>Це автоматичний службовий лист.'}</div></td></tr></table><div style="max-width:600px;margin:14px auto 0;color:#8b96a8;font-size:11px;line-height:1.5;text-align:center">Безпечний зв’язок у подорожах · Signal eSIM</div></td></tr></table></body></html>`;
}

function messageCard(message, tone='blue') { const color={blue:'#4f6cff',violet:'#7c3aed',red:'#ef4444',green:'#16a34a'}[tone]||'#4f6cff';return `<div style="background:#f6f8fc;border-left:4px solid ${color};border-radius:12px;padding:18px 19px;color:#26344c;font-size:15px;line-height:1.75">${escapeHtml(message).replace(/\n/g,'<br>')}</div>`; }

function verificationCode({code}) { return layout({eyebrow:'БЕЗПЕКА АКАУНТА',title:'Код підтвердження',intro:'Введіть цей одноразовий код у застосунку Signal.',content:`<div style="font-size:34px;font-weight:900;letter-spacing:9px;text-align:center;background:#f1f4fa;border-radius:15px;padding:19px;color:#172033">${escapeHtml(code)}</div><p style="color:#68758b;font-size:13px;line-height:1.65;margin-top:16px">Код діє 10 хвилин. Нікому його не повідомляйте. Якщо ви не робили запит — просто проігноруйте лист.</p>`}); }
function supportReply({ticketId,subject,message}) { return layout({eyebrow:`ПІДТРИМКА · ЗВЕРНЕННЯ #${ticketId}`,title:'Маємо нову відповідь для вас',intro:subject,content:messageCard(message),action:{label:'Відкрити звернення',url:`/ticket.html?id=${ticketId}`},footer:`Ви можете відповісти на цей лист — повідомлення буде додано до звернення #${escapeHtml(ticketId)}.<br><br>З повагою,<br><strong>Команда підтримки Signal</strong>`}); }
function ticketAssignment({ticketId,customerEmail,subject}) { return layout({eyebrow:'АДМІН-ПАНЕЛЬ · НОВЕ ПРИЗНАЧЕННЯ',title:`Вам призначено звернення #${ticketId}`,intro:'Super Admin передав вам звернення для подальшої роботи.',content:`<div style="background:#f6f8fc;border-radius:12px;padding:17px 19px;font-size:14px;line-height:1.8"><strong>Користувач:</strong> ${escapeHtml(customerEmail)}<br><strong>Тема:</strong> ${escapeHtml(subject)}</div>`,action:{label:'Перейти до звернення',url:`/admin-ticket.html?id=${ticketId}`}}); }
function purchaseReceipt({purchase,receiptUrl,fulfillmentStatus}) { const amount=purchase.amountCents==null?'—':`${(Number(purchase.amountCents)/100).toFixed(2)} ${String(purchase.currency||'').toUpperCase()}`;const plan=purchase.packageName||purchase.plan||'eSIM-пакет';const detail=[purchase.location,purchase.dataLimitGb==null?null:`${purchase.dataLimitGb} ГБ`,purchase.durationDays?`${purchase.durationDays} днів`:null].filter(Boolean).join(' · ');const status=fulfillmentStatus==='provisioned'?'eSIM успішно видано':fulfillmentStatus==='failed'?'Оплату прийнято; підтримка вже бачить проблему з видачею eSIM':'Оплату успішно прийнято';return layout({eyebrow:'ПІДТВЕРДЖЕННЯ ОПЛАТИ',title:'Дякуємо за покупку!',intro:'Оплату проведено, а чек збережено у вашому акаунті.',content:`<div style="background:#f6f8fc;border-radius:12px;padding:18px 20px;font-size:14px;line-height:1.85"><strong>Покупка:</strong> ${escapeHtml(plan)}<br>${detail?`<strong>Пакет:</strong> ${escapeHtml(detail)}<br>`:''}<strong>Сума:</strong> ${escapeHtml(amount)}<br><strong>Дата:</strong> ${escapeHtml(new Date(purchase.paidAt||Date.now()).toLocaleString('uk-UA'))}<br><strong>Номер:</strong> ${escapeHtml(purchase.id)}<br><strong>Статус:</strong> ${escapeHtml(status)}</div>`,action:{label:receiptUrl?'Відкрити чек Stripe':'Переглянути історію оплат',url:receiptUrl||'/payments.html'}}); }
function twoFactorCode({code,purpose='login'}) { const title=purpose==='enable'?'Підтвердьте ввімкнення 2FA':purpose==='disable'?'Підтвердьте вимкнення 2FA':'Підтвердьте вхід в адмін-панель';return layout({eyebrow:'БЕЗПЕКА АДМІН-ПАНЕЛІ',title,intro:'Введіть цей одноразовий код у вікні підтвердження.',content:`<div style="font-size:34px;font-weight:900;letter-spacing:9px;text-align:center;background:#f1f4fa;border-radius:15px;padding:19px;color:#172033">${escapeHtml(code)}</div><p style="color:#68758b;font-size:13px;line-height:1.65;margin-top:16px">Код діє 10 хвилин і допускає не більше п’яти спроб. Нікому його не повідомляйте.</p>`}); }
function broadcast({title,message,audience='customers',senderEmail=''}) { const staff=audience==='staff';return layout({eyebrow:staff?'ВНУТРІШНЯ РОЗСИЛКА · КОМАНДА':'НОВИНИ ДЛЯ КЛІЄНТІВ',title,intro:staff?'Важливе повідомлення для працівників адмін-панелі.':'Нове повідомлення від команди Signal.',content:`${messageCard(message,staff?'violet':'blue')}${staff&&senderEmail?`<p style="margin:16px 2px 0;color:#78859a;font-size:12px">Надіслав Super Admin: ${escapeHtml(senderEmail)}</p>`:''}`}); }
function adminSecurityAlert({title,message}) { return layout({eyebrow:'БЕЗПЕКА АДМІН-ПАНЕЛІ',title,intro:'Зафіксовано важливу зміну способу входу.',content:messageCard(message,'red')}); }
function notification({title,message,actionUrl='/dashboard.html',actionLabel='Відкрити застосунок'}) { return layout({eyebrow:'ПОВІДОМЛЕННЯ SIGNAL',title,intro:'Нове повідомлення від команди Signal.',content:messageCard(message),action:{label:actionLabel,url:actionUrl}}); }
function accessRecovery({url,expiresAt}) { return layout({eyebrow:'ВІДНОВЛЕННЯ ДОСТУПУ',title:'Безпечне посилання готове',intro:'Підтримка Signal підтвердила ваш запит на відновлення акаунта.',content:`<p style="font-size:14px;line-height:1.7;color:#526078">Посилання одноразове та діє до <strong>${escapeHtml(new Date(expiresAt).toLocaleString('uk-UA'))}</strong>. Ви зможете задати новий email, пароль і 6-значний PIN.</p>`,action:{label:'Задати нові дані входу',url},footer:'Якщо ви не подавали цей запит, не відкривайте посилання та зверніться в підтримку.<br><br><strong>Команда безпеки Signal</strong>'}); }
function esimInstructions({activationCode}) { return layout({eyebrow:'ІНСТРУКЦІЯ eSIM',title:'Ваша eSIM готова до встановлення',intro:'Відкрийте Signal → Профіль → Керування eSIM та дотримуйтеся інструкції.',content:`<div style="background:#f6f8fc;border-radius:12px;padding:18px;font-size:14px"><div style="color:#78859a;font-size:11px;font-weight:800;letter-spacing:1px">КОД АКТИВАЦІЇ</div><div style="margin-top:8px;font-family:monospace;font-size:17px;font-weight:800;word-break:break-all;color:#172033">${escapeHtml(activationCode)}</div></div><p style="color:#68758b;font-size:13px;line-height:1.65">Не передавайте код іншим людям і не публікуйте скриншот QR-коду.</p>`,action:{label:'Відкрити керування eSIM',url:'/esim-management.html'}}); }

module.exports={escapeHtml,absoluteUrl,layout,verificationCode,supportReply,ticketAssignment,purchaseReceipt,twoFactorCode,broadcast,adminSecurityAlert,notification,accessRecovery,esimInstructions};
